### ISSUE TITLE
Unable to parse blank line

### ISSUE THREAD

**Issue by osdu** [jow-/lucihttp#2]
If the textarea has multiple lines and the last line is not a blank line but a single character, the textarea value will not be obtained.

*ok*

`name="cbid.crontab.1.crons"\r\n\r\nA\r\nB\r\n\r\n`

```
curl 'http://192.168.1.1/cgi-bin/luci/admin/system/crontab' \
-H 'Cookie: sysauth=4dc363e1d0a940b9e31931599ad511d4' \
-H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0IAtYXyyDSLQg8kg' \
--data-binary $'------WebKitFormBoundary0IAtYXyyDSLQg8kg\r\nContent-Disposition: form-data; name="cbid.crontab.1.crons"\r\n\r\nA\r\nB\r\n\r\n------WebKitFormBoundary0IAtYXyyDSLQg8kg--\r\n'  \
--compressed >/dev/null;
```

*error*

`name="cbid.crontab.1.crons"\r\n\r\nA\r\nB\r\n`

```
curl 'http://192.168.1.1/cgi-bin/luci/admin/system/crontab' \
-H 'Cookie: sysauth=4dc363e1d0a940b9e31931599ad511d4' \
-H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0IAtYXyyDSLQg8kg' \
--data-binary $'------WebKitFormBoundary0IAtYXyyDSLQg8kg\r\nContent-Disposition: form-data; name="cbid.crontab.1.crons"\r\n\r\nA\r\nB\r\n------WebKitFormBoundary0IAtYXyyDSLQg8kg--\r\n'  \
--compressed >/dev/null;
```

**Comment by osdu** [comment]
@jow- 

If the textarea has only one line and is not a blank line, the textarea value will still not be obtained.

**Comment by jow-** [comment]
Can you provide a test case? I cannot reproduce that. The following works fine for me:

```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0IAtYXyyDSLQg8kg
X-Comment: Test parsing single character without trailing newline (https://github.com/jow-/lucihttp/issues/2)
X-Expect-Part-Value: A

------WebKitFormBoundary0IAtYXyyDSLQg8kg
Content-Disposition: form-data; name="cbid.crontab.1.crons"

A
------WebKitFormBoundary0IAtYXyyDSLQg8kg--
```

**Comment by osdu** [comment]
use luci test
https://github.com/openwrt/luci/issues/2737

**Comment by jow-** [comment]
The library has not yet been updated in LuCI. WHen I changed liblucihttp.so with the locally compiled one I cannot reproduce the issue.

**Comment by osdu** [comment]
Save the first normal, the second exception

**Comment by jow-** [comment]
Ok, I can reproduce that now. It is unrelated to the lucihttp parsing issue however but the symptom of another bug.

By default, the LuCI CBI does not store a value if it is identical to the value being saved. In most cases it works because the browser sends content with `\r\n` line endings, LuCI converts it to `\n` and writes it to the file.

When the same content is sent the next time, it will be different (`foo\r\n` vs. `foo\n`) from LuCI's pov and written to the file again. However when you send a sole line without a newline, LuCI will receive `foo`, write `foo` to the file and on the next submission, `foo` is seen to be identical to `foo`, the value passed to `SimpleForm.handle()` will be unset and an empty string is written to the file.

Will fix this in a separate commit.
